# Generated by Django 3.1 on 2020-08-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='USERS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(choices=[('consumer', 'CONSUMER'), ('provider', 'PROVIDER')], default='provider', max_length=240)),
                ('first_name', models.CharField(max_length=250)),
                ('second_name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=140, unique=True)),
                ('password', models.CharField(max_length=250)),
            ],
        ),
    ]
