# Generated by Django 3.1 on 2020-08-24 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ECP', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='USERS',
            new_name='Signup',
        ),
    ]
