# Generated by Django 3.1 on 2020-08-25 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ECP', '0004_auto_20200825_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='user',
            field=models.CharField(choices=[('2', 'CONSUMER'), ('1', 'PROVIDER')], default='1', max_length=240),
        ),
    ]
